# Generated by Django 4.0.7 on 2022-09-29 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dcim', '0161_cabling_cleanup'),
        ('virtualization', '0032_virtualmachine_update_sites'),
        ('ipam', '0060_alter_l2vpn_slug'),
        ('netbox_orb', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policycloudprober',
            name='devices',
        ),
        migrations.AddField(
            model_name='policycloudprober',
            name='devices',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dcim.device'),
        ),
        migrations.RemoveField(
            model_name='policycloudprober',
            name='services',
        ),
        migrations.AddField(
            model_name='policycloudprober',
            name='services',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ipam.service'),
        ),
        migrations.RemoveField(
            model_name='policycloudprober',
            name='vms',
        ),
        migrations.AddField(
            model_name='policycloudprober',
            name='vms',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='virtualization.virtualmachine'),
        ),
        migrations.DeleteModel(
            name='AgentPolicy',
        ),
    ]
